### ISSUE TITLE
Update README with compilation instructions

### ISSUE THREAD

**Issue by pacho2** [gecrooks/weblogo#172]
Hello,

I want to compile and install weblogo-3.8.0 on a specific (non default) prefix, and I wonder about the right procedure to call setup.py or make. For now, it seems that I need to run:
```
./setup.py build
./setup.py install --prefix=...
```

Thanks a lot for documenting it :)

**Comment by pacho2** [comment]
Sadly it seems to later fail to run with:
```
$ ./weblogo 
Traceback (most recent call last):
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 397, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pacho/public_html/cgi-bin/ADAPTABLE/weblogo-3.8.0-sources/weblogo/./weblogo", line 33, in <module>
    sys.exit(load_entry_point('weblogo==3.8.0', 'console_scripts', 'weblogo')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pacho/public_html/cgi-bin/ADAPTABLE/weblogo-3.8.0-sources/weblogo/./weblogo", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 862, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 399, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for weblogo
```

**Comment by gecrooks** [comment]
WebLogo's configuration is way out of date. I'm going to release a new version 3.9 within a couple of weeks to deal with issues arising from python 3.13, so I'll see if I can fix this up too.
